MAX_BATCH_SCREENSHOTS = 50  # per-cycle upload cap; ~1 MB each ≈ 50 MB, enough to stay ahead of ~1/s capture rate
RETENTION_SECONDS = 6 * 60 * 60  # null png_data after 6h (capture-side guard backstops at 8h)
REQUEST_TIMEOUT_SECONDS = 60
KEYRING_SERVICE_NAME = "luminque-sender"
API_SCREENSHOTS_PATH = "/v1/screenshots"
API_HEARTBEAT_PATH = "/v1/heartbeat"
DB_FILENAME = "recording.db"
STATE_FILENAME = "sender_state.json"
LOG_DIR = "logs"
