terraform {
  required_version = ">= 1.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Partial configuration: bucket/key/region/dynamodb_table come from
  # backend.hcl (generated by scripts/bootstrap-state.sh, gitignored so the
  # account id never lands in the repo).
  #   terraform init -backend-config=backend.hcl
  backend "s3" {}
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      project    = "luminque"
      managed-by = "terraform"
    }
  }
}
